services:
  backend:
    image: ghcr.io/sander1384/albumdeck-backend:latest
    container_name: albumdeck-backend
    restart: unless-stopped
    environment:
      NAVIDROME_URL: "https://music.example.com"
      NAVIDROME_USER: "your_user"
      NAVIDROME_PASS: "your_pass_or_token"
      NAVIDROME_CLIENT: "albumdeck-app"
      NAVIDROME_ALLOW_INSECURE_TLS: "false"
      APP_PORT: "8877"
    ports:
      - "8877:8877"
    volumes:
      - /volume1/docker/albumdeck/backend-data:/app/.data

  frontend:
    image: ghcr.io/sander1384/albumdeck-frontend:latest
    container_name: albumdeck-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8080:80"
