services:
  backend:
    image: ghcr.io/sander1384/albumdeck-backend:latest
    container_name: albumdeck-backend
    env_file:
      - .env
    ports:
      - "8877:8877"
    volumes:
      - backend_data:/app/.data
    restart: unless-stopped

  frontend:
    image: ghcr.io/sander1384/albumdeck-frontend:latest
    container_name: albumdeck-frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
    restart: unless-stopped

volumes:
  backend_data:
