services:
  albumdeck:
    image: ghcr.io/sander1384/albumdeck:v0.3.49
    container_name: albumdeck
    env_file:
      - .env
    environment:
      APP_PORT: "8080"
    ports:
      - "8080:8080"
    volumes:
      - backend_data:/app/.data
    restart: unless-stopped

volumes:
  backend_data:
